name: Bump Version

on:
  workflow_dispatch:
    inputs:
      semver:
        description: Semantic Version Bump
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump_version_and_tag:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install bump2version~=1.0
      - name: "Run 'bump-${{ github.event.inputs.semver }}' Make Target"
        run: "make bump-${{ github.event.inputs.semver }}"
      - name: Push Commit and Tags
        run: |
          git push origin master
          git push origin --tags
